import { Hono } from "hono";
import type { Env } from "../types";

const PRODUCT = "inference";

const inference = new Hono<{ Bindings: Env }>();

const MODELS: Record<string, { id: string; description: string; context: number }> = {
  "llama-3": {
    id: "@cf/meta/llama-3.1-8b-instruct",
    description: "Llama 3.1 8B — fast, general purpose. Good for summarisation, Q&A, classification.",
    context: 8192,
  },
  "mistral": {
    id: "@cf/mistral/mistral-7b-instruct-v0.1",
    description: "Mistral 7B — instruction-tuned, efficient for structured tasks.",
    context: 8192,
  },
  "qwen": {
    id: "@cf/qwen/qwen1.5-7b-chat-awq",
    description: "Qwen 1.5 7B — strong multilingual support.",
    context: 8192,
  },
};

const DEFAULT_MODEL = "llama-3";

// POST /api/inference/complete — single-turn text completion
inference.post("/complete", async (c) => {
  let body: any;
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "Request body must be JSON" }, 400);
  }

  const prompt = String(body?.prompt ?? "").trim();
  if (!prompt) return c.json({ error: "Missing 'prompt' field" }, 400);
  if (prompt.length > 4000) return c.json({ error: "Prompt too long (max 4000 characters)" }, 400);

  const modelKey = (body?.model ?? DEFAULT_MODEL).toLowerCase();
  const model = MODELS[modelKey];
  if (!model) {
    return c.json({ error: `Unknown model '${modelKey}'. Use: ${Object.keys(MODELS).join(", ")}` }, 400);
  }

  const maxTokens = Math.min(parseInt(body?.max_tokens ?? "512"), 2048);
  const systemPrompt = body?.system ? String(body.system).slice(0, 1000) : undefined;

  const messages: { role: string; content: string }[] = [];
  if (systemPrompt) messages.push({ role: "system", content: systemPrompt });
  messages.push({ role: "user", content: prompt });

  try {
    const result: any = await (c.env.AI as any).run(model.id, {
      messages,
      max_tokens: maxTokens,
    });

    const text = result?.response ?? result?.result?.response ?? result?.choices?.[0]?.message?.content ?? "";

    return c.json({
      product: PRODUCT,
      data: {
        model: modelKey,
        prompt,
        response: text,
        tokens_used: result?.usage?.total_tokens ?? null,
      },
      disclaimer: "Responses are generated by a small open-source model. Verify critical information.",
      timestamp: new Date().toISOString(),
    });
  } catch (e: any) {
    return c.json({ error: "Inference failed" }, 503);
  }
});

// POST /api/inference/chat — multi-turn chat
inference.post("/chat", async (c) => {
  let body: any;
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "Request body must be JSON" }, 400);
  }

  const messages: { role: string; content: string }[] = body?.messages;
  if (!Array.isArray(messages) || messages.length === 0) {
    return c.json({ error: "Missing 'messages' array. Each message needs role and content." }, 400);
  }

  if (messages.length > 20) return c.json({ error: "Too many messages (max 20)" }, 400);

  const modelKey = (body?.model ?? DEFAULT_MODEL).toLowerCase();
  const model = MODELS[modelKey];
  if (!model) {
    return c.json({ error: `Unknown model. Use: ${Object.keys(MODELS).join(", ")}` }, 400);
  }

  const maxTokens = Math.min(parseInt(body?.max_tokens ?? "512"), 2048);

  try {
    const result: any = await (c.env.AI as any).run(model.id, {
      messages: messages.map((m) => ({ role: m.role, content: String(m.content).slice(0, 2000) })),
      max_tokens: maxTokens,
    });

    const text = result?.response ?? result?.result?.response ?? result?.choices?.[0]?.message?.content ?? "";

    return c.json({
      product: PRODUCT,
      data: {
        model: modelKey,
        response: text,
        message_count: messages.length,
        tokens_used: result?.usage?.total_tokens ?? null,
      },
      timestamp: new Date().toISOString(),
    });
  } catch (e: any) {
    return c.json({ error: "Inference failed" }, 503);
  }
});

inference.get("/models", (c) => c.json({
  product: PRODUCT,
  data: { models: MODELS, default: DEFAULT_MODEL },
  timestamp: new Date().toISOString(),
}));

inference.get("/", (c) => c.json({
  error: "POST to /api/inference/complete or /api/inference/chat",
  docs: "https://api.devdrops.run/openapi.json",
  examples: [
    { endpoint: "POST /api/inference/complete", body: { prompt: "Summarise the key risks of investing in AI startups", model: "llama-3" } },
    { endpoint: "POST /api/inference/chat", body: { messages: [{ role: "user", content: "What is x402?" }], model: "mistral" } },
  ],
}, 400));

export default inference;
